spring.cassandra.keyspace-name=test_keyspace
spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042


spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=create_if_not_exists

spring.security.user.name=admin
spring.security.user.password=admin123

external.api.users=https://jsonplaceholder.typicode.com/users
external.api.posts=https://jsonplaceholder.typicode.com/posts